### PR TITLE
Removing zscale, unittest and addressing review comments

### PR DESCRIPTION
**Pull request by bsipocz**
* [x] - clean up tests, transform unittest to pure pytest
 * [x] use astropy zscale
 * [x] making mpl optional dependency for tests, etc
 * [x] remove ``writeRGB`` and ``displayRGB`` as @cdeil suggested
 * [x] adding Returns to the docstring
 * some small additional improvements

### CODE REVIEW

**Comment by bsipocz** [comment]
@parejkoj  - Since the astropy travis is rather clogged, could you switch on testing on your fork for pull requests? I'm currently testing this on my fork for any push, but in general it's better only to have on for PRs.

**Comment by parejkoj** [comment]
Is turning on CI on my fork easy? I can't find an obvious button.

**Comment by parejkoj** [comment]
Ah, I think I found it: https://github.com/astropy/astropy/wiki/Continuous-Integration#staging-branches

I've done that, but I'm not sure if that's all that was needed.

**Comment by parejkoj** [comment]
Though I see your point about removing the write and display methods, it was very helpful when debugging to be able to display in the tests. Can we put a display method into the test file?

**Comment by parejkoj** [comment]
Other than not having the display option in the tests, your changes look good.

**Comment by bsipocz** [comment]
@parejkoj - Sorry for not answering these sooner, I wasn't around my desk. 

For the travis CI stuff, I think that wiki page is very obsolete. What you need to do is go to https://travis-ci.org/, sign in with your github account. Then you will see a list of your repositories, including the forks:

screen shot 2016-12-02 at 23 41 09

Then with the x sliders you can switch on the testing on a given repo, and use the setting with the cogwheel.  Usually it's advisable to have it turned on on PRs, but not on pushes, so test will run if someone elses contributes to one of your branches, but not when you push to those (e.g. you won't double test for each commit you do on a branch you already have a PR to the main repo)
screen shot 2016-12-02 at 23 43 36

**Comment by parejkoj** [comment]
Got it, thanks.

**Pull request merged**
