### PR TITLE
Adding functions and classes to the public API

### PR DESCRIPTION
**Pull request by bsipocz**
To be able to check the sphinx output of the docstrings.

Also, some docstring cleanup.

### CODE REVIEW

**Comment by bsipocz** [comment]
@parejkoj - Is there any chance to dust off this branch before the feature freeze (this friday)? I can put in a few hours in terms of cleanup etc, or even can open a PR from this branch of yours.

**Comment by parejkoj** [comment]
Yeah, I was thinking about this. It'd be really nice to get it into 0.13. Let me poke at it tomorrow and see how things stand.

**Comment by parejkoj** [comment]
Ok, I've rebased myself onto astropy upstream master. Should I just merge in your changes now and we can see what else needs to be cleaned up on my branch?

**Comment by bsipocz** [comment]
@parejkoj - There are merge conflicts here as you already have cleaned up a bit, so I'll also have to rebase this PR. I remember doing that locally already, but I left my laptop at work, so will push it back here tomorrow morning. In the meantime you can open a PR on astropy to let travis run.

**Comment by bsipocz** [comment]
@parejkoj - I've rebased this here again, so you can merge into your branch before opening a PR to astropy. I think biggest tasks will be to get rid of the zscale function and use that one that's already in astropy and to write some narrative docs.

**Pull request merged**
